Controllers/EmployeesListController.cs
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SportActivities.Data;
using SportActivities.Models;
using SportActivities.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
//using System.Net.Http.Formatting;
using Newtonsoft.Json.Linq;
using System.IO;
using System.Text;
using Microsoft.AspNetCore.Http;
using System.Xml.Linq;
using Newtonsoft.Json;

namespace SportActivities.Controllers
{
   
    [Authorize(Roles = "admin")]
    public class EmployeesListController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<Employee> userManager;
        private readonly ApplicationDbContext context;


        public EmployeesListController(RoleManager<IdentityRole> roleMgr, UserManager<Employee> usrMgr, ApplicationDbContext appDbContext)
        {
            userManager = usrMgr;
            roleManager = roleMgr;
            context = appDbContext;
        }
        public IActionResult EmployeeTable()
        {
            return View();
        }



        [HttpGet]
        public async Task<object> Get(DataSourceLoadOptions loadOptions)
        {
            var dto = (from employee in context.Employees
                     join choice in context.Choices on employee.Id equals choice.EmployeeId into temp
                     from newTemp in temp.DefaultIfEmpty()
                     select new dto_EmployeeTable
                     {
                         Id = employee.Id,
                         FirstName = employee.FirstName,
                         LastName = employee.LastName,
                         Email = employee.Email,
                         DefaultActivity = newTemp.DefaultActivity != null ? newTemp.DefaultActivity.Name: "-",
                         FirstActivity = newTemp.FirstActivity != null ? newTemp.FirstActivity.Name : "-",
                     });

            
            return await DataSourceLoader.LoadAsync(dto, loadOptions);
        }



        [HttpPost]
        public async Task<IActionResult> Create(string values)
        {
            Employee newEmployee = new Employee();
            JsonConvert.PopulateObject(values, newEmployee);
            newEmployee.UserName = newEmployee.Email;
            newEmployee.EmailConfirmed = true;

            IdentityResult resultCreateEmployee = await userManager.CreateAsync(newEmployee, "PeoplePower@1234");
            IdentityResult resultAsignRoleToEmployee = await userManager.AddToRoleAsync(newEmployee, "basic");
            if (resultCreateEmployee.Succeeded && resultAsignRoleToEmployee.Succeeded)
                return Ok(newEmployee);
            else
            {
                foreach (IdentityError error in resultCreateEmployee.Errors)
                    ModelState.AddModelError("", error.Description);
                foreach (IdentityError error in resultAsignRoleToEmployee.Errors)
                    ModelState.AddModelError("", error.Description);
            }
            return Ok(newEmployee);
        }

        [HttpPut]
        public async Task<IActionResult> Update(string id, string values)
        {
            Employee employee = await userManager.FindByIdAsync(id);
            JsonConvert.PopulateObject(values, employee);

            IdentityResult result = await userManager.UpdateAsync(employee);
            return new EmptyResult();
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(string id)
        {
            Employee employee = await userManager.FindByIdAsync(id);
            if (employee != null)
            {
                IdentityResult result = await userManager.DeleteAsync(employee);
            }
            return Ok();
        }
        //needs testing
        public ActionResult GetListOfEmployeesWithValidChoice()
        {

            var query = from employee in userManager.Users
                        join choice in context.Choices on employee.Id equals choice.Employee.Id
                        where choice.FirstActivity != null || choice.DefaultActivity != null
                        select new Employee { Id = employee.Id, FirstName = employee.FirstName, LastName = employee.LastName, Email = employee.Email };

            var viewModel = new EmployeeViewModel { Employees = query.ToList() };
            return View(viewModel);
        }
    
        //for development
        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }
    }

}

Views/Shared/_Approved.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

@{
    ViewData["Title"] = "Approved Activities";
}

<h2>@ViewData["Title"]</h2>


<div class="demo-container">
    <div id="approvedContainer"></div>
</div>

<script>

    var customDataSource;

    $(function () {
        customDataSource = new DevExpress.data.CustomStore({
            key: "ActivityId",
            load: function (loadOptions) {
                return $.getJSON("/Home/ApprovedActivities")
                    .fail(function () { throw "Data loading error" });
            },
        });
    });

    $(function () {
        function logEvent(eventName) {
            var logList = $("#events ul"),
                newItem = $("<li>", { text: eventName });

            logList.prepend(newItem);
        }

        $("#approvedContainer").dxDataGrid({
            dataSource: customDataSource,
            keyExpr: "ActivityId",
            showBorders: true,
            paging: {
                enabled: false
            },
            editing: {
                mode: "row",
            },
            columns: [

                {
                    dataField: "Name",
                    caption: "Activity Name"
                },

                {
                    type: "buttons",
                    buttons: [{
                        text: "Choose",
                        hint: "Choose an activity",
                        onClick: function (e) {

                            $.ajax({
                                url: "/Home/HasApprovedSelected/" + e.row.data.ActivityId,
                                method: 'GET',
                                //dataType: text,
                                success: function (data) {
                                    var message = 'Confirm selection?';
                                    if (data == true) {
                                        message = 'You already have an approved sport selected. Confirm the change?';
                                    }

                                    if (confirm(message)) {

                                        return $.ajax({

                                            url: "/Home/SetDefaultActivityId/" + e.row.data.ActivityId,
                                            success: function () {

                                                alert('Congratulations! You updated your approved activity!')
                                            },
                                            error: function () { throw "Update failed." }
                                        });
                                    }

                                }

                            });
                        },
                    }
                    ]
                }
            ],
        });

        $("#clear").dxButton({
            text: "Clear",
            onClick: function () {
                $("#events ul").empty();
            }
        });
    });

</script>

Views/Shared/_DevExtremeLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SportActivities</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @* Uncomment to use the HtmlEditor control *@
    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.min.js"></script> *@

    @* Uncomment to use the Gantt control *@
    @*<link href="~/css/devextreme/dx-gantt.css" rel="stylesheet" />*@

    @* Uncomment to use the Diagram control *@
    @*<link href="~/css/devextreme/dx-diagram.css" rel="stylesheet" />*@

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />

    <link href="~/css/devextreme/dx.common.css" rel="stylesheet" />

    @* Predefined themes: https://js.devexpress.com/DevExtreme/Guide/Themes_and_Styles/Predefined_Themes/ *@
    <link href="~/css/devextreme/dx.generic.sport-activies.css" rel="stylesheet" />

    @* Uncomment to use the Gantt control *@
    @*<script src="~/js/devextreme/dx-gantt.js"></script>*@

    @* Uncomment to use the Diagram control *@
    @*<script src="~/js/devextreme/dx-diagram.js"></script>*@

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>

    @* Uncomment to use Globalize for localization *@
    @* Docs: https://docs.devexpress.com/AspNetCore/400577#globalize *@
    @*<script src="~/js/devextreme/cldr.js"></script>*@
    @*<script src="~/js/devextreme/cldr/event.js"></script>*@
    @*<script src="~/js/devextreme/cldr/supplemental.js"></script>*@
    @*<script src="~/js/devextreme/cldr/unresolved.js"></script>*@
    @*<script src="~/js/devextreme/globalize.js"></script>*@
    @*<script src="~/js/devextreme/globalize/message.js"></script>*@
    @*<script src="~/js/devextreme/globalize/number.js"></script>*@
    @*<script src="~/js/devextreme/globalize/currency.js"></script>*@
    @*<script src="~/js/devextreme/globalize/date.js"></script>*@

    @* Uncomment to enable client-side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@

    <script src="https://cdn3.devexpress.com/jslib/20.1.7/js/dx.all.js"></script>

    @* Uncomment to provide geo-data for the VectorMap control *@
    @* Docs: https://js.devexpress.com/DevExtreme/Guide/Widgets/VectorMap/Providing_Data/#Data_for_Areas *@
    @*<script src="~/js/devextreme/vectormap-data/world.js"></script>*@

    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
    <script src="~/js/site.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/header-footer.css" />
</head>


<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <a class="navbar-brand" href="/"><img src="/images/logo.png" style="height:40px;"></a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navbar" class="collapse navbar-collapse">

            <ul class="menu navbar-nav mr-auto">
                <li>
                    <a class="nav-link" href="/">Sport Activities</a>
                </li>

                @if (SignInManager.IsSignedIn(User) && User.IsInRole("admin"))
                {
                    <li>
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="TopActivities">Pending Activities</a>
                    </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="EmployeesList" asp-action="EmployeeTable">Employees List</a>
                </li>

                }
            </ul>

            <partial name="_LoginPartial" />
        </div>
    </nav>

    <main role="main" class="container">
        @RenderBody()
    </main>
    <footer class="border-top footer text-muted">
        <div class="d-flex align-items-center">
            <img class="footer-img" src="~/images/img1.jpg" />
            <span class="footer-copyright">
                &copy; Team1 - SportActivities
            </span>
        </div>
    </footer>
</body>



    @RenderSection("Scripts", required: false)






</html>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SportActivities</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    @if (SignInManager.IsSignedIn(User))
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SportActivities</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Table">Employees Table</a>
                            </li>

                          
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    }


    <div class="container">
        
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SportActivities - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_PendingActivities.cshtml
@{
    ViewData["Title"] = "Pending Activities";
}



<h2>@ViewData["Title"]</h2>


<div class="dx-viewport demo-container">

    <div id="gridContainer"></div>

</div>

<script>
    var customDataSource;

    $(function () {
        customDataSource = new DevExpress.data.CustomStore({
            key: "ActivityId",
            load: function (loadOptions) {
                return $.getJSON("/Home/WaitingForApprovalActivities")
                    .fail(function () { throw "Data loading error" });
            },
            insert: function (values) {
                return $.ajax({
                    url: "/Home/AddNewActivity",
                    method: "POST",
                    data: values
                });
            }


        });
    });

    function hrCheck() {
            if (@User.IsInRole("admin").ToString().ToLowerInvariant() && !@ViewBag.Message.ToString().ToLowerInvariant())
                    return true;
            return false;
    }

    $(function () {

        $("#gridContainer").dxDataGrid({
            dataSource: customDataSource,
            keyExpr: "ActivityId",
            showBorders: true,
            paging: {
                enabled: false
            },
            editing: {
                mode: "row",
                allowUpdating: true,
                allowDeleting: true,
                allowAdding: true
            },
            columns: [
                {
                    dataField: "Name",
                    caption: "Activity Name",
                    validationRules: [{ type: "required" }]
                },

                {
                    //Choose button
                    type: "buttons",
                    buttons: [{
                        text: "Choose",
                        name: "choose",
                        hint: "Choose an activity",
                        visible: function (e) {
                            return !e.row.isInserting && !e.row.isEditing && !hrCheck();
                        },
                        onClick: function (e) {
                            //return $.ajax({
                            //    url: "/Home/SetFirstActivityId/" + e.row.data.ActivityId,
                            //    success: function () { alert('Congratulations! You just chose your first activity!') },
                            //    error: function () { throw "The choice failed." }
                            //});
                            $.ajax({
                                url: "/Home/HasPendingSelected/" + e.row.data.ActivityId,
                                method: 'GET',
                                //dataType: text,
                                success: function (data) {
                                    var message = 'Confirm selection?';
                                    if (data == true) {
                                        message = 'You already have a pending sport selected. Confirm the change?';
                                    }

                                    if (confirm(message)) {

                                        return $.ajax({

                                            url: "/Home/SetFirstActivityId/" + e.row.data.ActivityId,
                                            success: function () {

                                                alert('Congratulations! You updated your chosen pending activity!')
                                            },
                                            error: function () { throw "Update failed." }
                                        });
                                    }

                                }

                            });
                        },
                    },
                    //Approve button
                    {
                        text: "Approve",
                        hint: "Approve an entry",
                        visible: hrCheck(),
                        onClick: function (e) {
                            return $.ajax({
                                url: "/Home/AproveActivity/" + e.row.data.ActivityId,
                                success: function () {
                                    alert('Activity approved'),
                                    $("#gridContainer").dxDataGrid("instance").refresh();
                                },
                                error: function () { throw "Approve failed" }
                            });

                        },
                    },
                    //Reject button
                    {
                        text: "Reject",
                        hint: "Reject an entry",
                        visible: hrCheck(),
                        onClick: function (e) {
                            return $.ajax({
                                url: "/Home/RejectActivity/" + e.row.data.ActivityId,
                                success: function () {
                                    alert('Activity rejected'),
                                    $("#gridContainer").dxDataGrid("instance").refresh();  
                                },
                                error: function () { throw "Reject failed" }
                            });
                        },
                    }
                    ]
                }
            ],
                       
        });


        $("#clear").dxButton({
            text: "Clear",
            onClick: function () {
                $("#events ul").empty();
            }
        });
    });

</script>

<style>
    #events {
        background-color: rgba(191, 191, 191, 0.15);
        padding: 20px;
        margin-top: 20px;
    }

        #events > div {
            padding-bottom: 5px;
        }

            #events > div:after {
                content: "";
                display: table;
                clear: both;
            }

        #events #clear {
            float: right;
        }

        #events .caption {
            float: left;
            font-weight: bold;
            font-size: 115%;
            line-height: 115%;
            padding-top: 7px;
        }

        #events ul {
            list-style: none;
            max-height: 100px;
            overflow: auto;
            margin: 0;
        }

            #events ul li {
                padding: 7px 0;
                border-bottom: 1px solid #dddddd;
            }

                #events ul li:last-child {
                    border-bottom: none;
                }
</style>

Views/Shared/_Rejected.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

@{
    ViewData["Title"] = "Rejected Activities";
}


<h2>@ViewData["Title"]</h2>


<div class="demo-container">
    <div id="rejectedContainer"></div>
</div>

<script>
    var customDataSource;
    $(function () {
        customDataSource = new DevExpress.data.CustomStore({
            key: "ActivityId",
            load: function (loadOptions) {
                return $.getJSON("/Home/RejectedActivities")
                    .fail(function () { throw "Data loading error" });
            },
            remove: function (key) {
                return $.ajax({
                    url: "/Home/DeleteActivity/" + key,
                    method: "DELETE",
                    success: function () { alert('Activity deleted') },
                    error: function () { throw "Deletion failed" }
                });
            },
        });
    });
    $(function () {
        function logEvent(eventName) {
            var logList = $("#events ul"),
                newItem = $("<li>", { text: eventName });

            logList.prepend(newItem);
        }

        function hrCheck() {
            if (@User.IsInRole("admin").ToString().ToLowerInvariant())
                    return true;
            return false;
        }

        $("#rejectedContainer").dxDataGrid({
            dataSource: customDataSource,
            keyExpr: "ActivityId",
            showBorders: true,
            paging: {
                enabled: false
            },
            editing: {
                mode: "row",
                allowDeleting: hrCheck(),
            },
            columns: [{
                dataField: "Name",
                caption: "Activity Name"
            }
            ],
            onRowRemoving: function (e) {
                logEvent("RowRemoving");
            },
            onRowRemoved: function (e) {
                logEvent("RowRemoved");
            }
        });

        @*
        $("#clear").dxButton({
            text: "Clear",
            onClick: function () {
                $("#events ul").empty();
            }
        });*@
    });
</script>